### ISSUE TITLE
Probes not firing due to missing `.probes` section

### ISSUE THREAD

**Issue by xxuejie** [cuviper/rust-libprobe#22] opened 2023-03-02 02:23 UTC
Hi, I was recently trying out this project, and I notice that probes are not firing correctly when using bpftrace.

My first thought is that something breaks in my test machine(I was using Ubuntu 22.04), but after some debugging, I was able to dig into code [here](https://github.com/iovisor/bcc/blob/9b5af1b0c140c8dbcbd9b821dccf2f7fceb6429c/src/cc/bcc_elf.c#L210-L215), for probes generated via this project, `semaphore_offset` will be 0, which then leads to code at [here](https://github.com/iovisor/bcc/blob/9b5af1b0c140c8dbcbd9b821dccf2f7fceb6429c/src/cc/bcc_elf.c#L302). So it seems that `bcc` (used by bpftrace underneath) is actually trying to find a `.probes` section, and use it to generate semaphore offsets. Without a `.probes` section, bpftrace will not be able to trigger SDT probes with semaphores.

Following [a tutorial](https://leezhenghui.github.io/linux/2019/03/05/exploring-usdt-on-linux.html#heading-prerequsiteseg-ubuntu) elsewhere(download `build.sh`, `tick-dtrace.d` and `tick-main.c`, then use `build.sh` to build the binary), I was able to build a C based binary with proper semaphore based USDT probes, that can be triggered via bpftrace. I compared the C binary with examples compiled from this project, and the only difference, is that Rust binaries lack `.probes` section. And it appears that `dtrace` generates this section when building `tick-dtrace.d` into `tick-dtrace.o`.

So my question is: is there a way we can replicate the same process, so as to provide legit `.probes` section here?

**Comment by xxuejie** [comment] 2023-03-02 02:27
It does seem to me that this particular `.probes` section is used to keep all the semaphore variables. This changes the question to: can we somehow organize those [semaphore variables](https://github.com/cuviper/rust-libprobe/blob/cd28b3ea43e853c29d76b12e23a9e007452fdd95/src/platform/systemtap.rs#L104) in a particular section?

**Comment by cuviper** [comment] 2023-03-02 02:36
Hmm, is that the root cause of #19? We can indeed add `#[link_section = ".probes"]`, as I mentioned in https://github.com/cuviper/rust-libprobe/pull/17#issuecomment-1110373422 -- I just didn't know why anyone needed that. :)

**Comment by xxuejie** [comment] 2023-03-02 02:36
Update: I found a solution to this problem, a proposed fix is included in #23

**Comment by xxuejie** [comment] 2023-03-02 02:37
Hmm, we are replying at almost the same time :)

Yes I think this is the root cause of #19

**Comment by cuviper** [comment] 2023-03-02 02:44
Great! So, I think the proposed split in #21 still has value to avoid the semaphore branch altogether, when it's not really needed, but if the section lets tools work better anyway, that's even better.

I'm going to merge my change first, so we can keep your attribution on the line in its new place. :)

**Comment by xxuejie** [comment] 2023-03-02 02:49
Yeah I totally agree that #21 has its own merits, it's just that #21 is not exactly a direct fix of #19. Those are separate issues :P

**Comment by cuviper** [comment] 2023-03-02 19:36
Released in 0.5.0.

**Closed by cuviper** 2023-03-02 19:36 UTC
